apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnia-node.fullname" . }}
  labels:
    app: {{ include "omnia-node.name" . }}
    chart: {{ include "omnia-node.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    app: {{ include "omnia-node.name" . }}
    release: {{ .Release.Name }}
