{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnia-node.serviceAccountName" . }}
  labels:
    app: {{ include "omnia-node.name" . }}
    chart: {{ include "omnia-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
