//! Groth16 prover and verifier for the Omnia rollup circuit.
//!
//! This module provides core operations for both the original [`RollupCircuit`]
//! and the [`crate::circuit::ExpandedRollupCircuit`]:
//!
//! - **Trusted setup** — Generate proving and verifying keys
//! - **Proof creation** — Create a Groth16 proof for a given circuit instance
//! - **Proof verification** — Verify a Groth16 proof against a verifying key
//!
//! All operations use the Bn254 pairing-friendly curve and the
//! [`ark_groth16`] implementation.
//!
//! ## Hash Function
//!
//! The expanded circuit uses Poseidon (Grassi et al. 2019) as its hash
//! function for both Merkle path verification and state transition
//! constraints. When constructing off-circuit Merkle trees for witness
//! data, use [`crate::merkle::poseidon_hash_to_fr`] to ensure the
//! off-circuit and on-circuit hash computations match.

use ark_bn254::Bn254;
use ark_crypto_primitives::snark::CircuitSpecificSetupSNARK;
use ark_groth16::Groth16;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;

use crate::circuit::{ExpandedRollupCircuit, RollupCircuit};

/// Errors that can occur during proving operations.
#[derive(Debug, thiserror::Error)]
pub enum ProverError {
    /// Error during trusted setup key generation.
    #[error("trusted setup failed: {0}")]
    SetupFailed(String),
    /// Error during proof creation.
    #[error("proof creation failed: {0}")]
    ProofCreationFailed(String),
    /// Error during proof verification.
    #[error("proof verification failed: {0}")]
    VerificationFailed(String),
    /// Error serializing or deserializing proof data.
    #[error("serialization error: {0}")]
    SerializationError(String),
    /// Error extracting public inputs from the circuit.
    #[error("circuit error: {0}")]
    CircuitError(String),
}

/// Proving key for Groth16 on Bn254.
pub type ProvingKey = ark_groth16::ProvingKey<Bn254>;

/// Verifying key for Groth16 on Bn254.
pub type VerifyingKey = ark_groth16::VerifyingKey<Bn254>;

/// Groth16 proof on Bn254.
pub type Proof = ark_groth16::Proof<Bn254>;

// ---------------------------------------------------------------------------
// Original RollupCircuit prover functions
// ---------------------------------------------------------------------------

/// Generate a trusted setup (proving key and verifying key) for the rollup
/// circuit.
///
/// The trusted setup is circuit-specific but input-agnostic: it only depends
/// on the structure of the circuit (number of constraints, witnesses, and
/// public inputs), not on the actual values. A dummy circuit with zero values
/// is used to determine the structure.
///
/// # Arguments
///
/// * `circuit` — A reference to a [`RollupCircuit`] used to determine the
///   circuit structure. The actual witness values are not used for setup.
///
/// # Errors
///
/// Returns [`ProverError::SetupFailed`] if the key generation fails.
pub fn generate_trusted_setup(circuit: &RollupCircuit) -> Result<(ProvingKey, VerifyingKey), ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    let dummy_circuit = RollupCircuit::empty();

    // Use the dummy circuit for setup since only the structure matters
    let _ = circuit; // suppress unused variable warning
    Groth16::<Bn254>::setup(dummy_circuit, &mut rng).map_err(|e| ProverError::SetupFailed(e.to_string()))
}

/// Create a Groth16 proof for the given circuit instance.
///
/// The proof can be verified by any party that holds the verifying key and
/// the public inputs.
///
/// # Arguments
///
/// * `circuit` — The [`RollupCircuit`] instance with assigned witnesses
///   and public inputs.
/// * `pk` — The proving key generated by [`generate_trusted_setup`].
///
/// # Errors
///
/// Returns [`ProverError::ProofCreationFailed`] if proof generation fails,
/// or [`ProverError::CircuitError`] if the public inputs cannot be extracted.
pub fn create_proof(circuit: RollupCircuit, pk: &ProvingKey) -> Result<Proof, ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    Groth16::<Bn254>::prove(pk, circuit, &mut rng).map_err(|e| ProverError::ProofCreationFailed(e.to_string()))
}

// ---------------------------------------------------------------------------
// ExpandedRollupCircuit prover functions
// ---------------------------------------------------------------------------

/// Generate a trusted setup (proving key and verifying key) for the expanded
/// rollup circuit.
///
/// The trusted setup is circuit-specific: it depends on the number of events
/// and the Merkle proof depth. A circuit with non-zero witness values and the
/// specified structure is used to ensure the proving key correctly constrains
/// all branches of the circuit.
///
/// # Arguments
///
/// * `num_events` — Number of events per batch (determines circuit structure)
/// * `merkle_depth` — Depth of each Merkle inclusion proof
///
/// # Errors
///
/// Returns [`ProverError::SetupFailed`] if the key generation fails.
///
/// # Security
///
/// Uses [`ExpandedRollupCircuit::for_setup()`] which provides non-zero witness
/// values, ensuring the setup ceremony produces keys that correctly constrain
/// the full circuit (including all conditional branches).
pub fn generate_trusted_setup_expanded(
    num_events: usize,
    merkle_depth: usize,
) -> Result<(ProvingKey, VerifyingKey), ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    let setup_circuit = ExpandedRollupCircuit::for_setup(num_events, merkle_depth);

    Groth16::<Bn254>::setup(setup_circuit, &mut rng).map_err(|e| ProverError::SetupFailed(e.to_string()))
}

/// Create a Groth16 proof for the given expanded circuit instance.
///
/// The proof can be verified by any party that holds the verifying key and
/// the public inputs.
///
/// # Arguments
///
/// * `circuit` — The [`ExpandedRollupCircuit`] instance with assigned witnesses
///   and public inputs.
/// * `pk` — The proving key generated by [`generate_trusted_setup_expanded`].
///
/// # Errors
///
/// Returns [`ProverError::ProofCreationFailed`] if proof generation fails.
pub fn create_expanded_proof(circuit: ExpandedRollupCircuit, pk: &ProvingKey) -> Result<Proof, ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    Groth16::<Bn254>::prove(pk, circuit, &mut rng).map_err(|e| ProverError::ProofCreationFailed(e.to_string()))
}

// ---------------------------------------------------------------------------
// Shared verification and serialization functions
// ---------------------------------------------------------------------------

/// Verify a Groth16 proof against a verifying key and public inputs.
///
/// # Arguments
///
/// * `vk` — The verifying key generated by [`generate_trusted_setup`] or
///   [`generate_trusted_setup_expanded`].
/// * `public_inputs` — The public inputs for the circuit.
/// * `proof` — The Groth16 proof to verify.
///
/// # Errors
///
/// Returns [`ProverError::VerificationFailed`] if the verification algorithm
/// fails (not if the proof is invalid — an invalid proof returns `Ok(false)`).
pub fn verify_proof(vk: &VerifyingKey, public_inputs: &[ark_bn254::Fr], proof: &Proof) -> Result<bool, ProverError> {
    Groth16::<Bn254>::verify(vk, public_inputs, proof).map_err(|e| ProverError::VerificationFailed(e.to_string()))
}

/// Serialize a Groth16 proof to bytes.
///
/// Uses canonical serialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if serialization fails.
pub fn serialize_proof(proof: &Proof) -> Result<Vec<u8>, ProverError> {
    let mut bytes = Vec::new();
    proof
        .serialize_uncompressed(&mut bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))?;
    Ok(bytes)
}

/// Deserialize a Groth16 proof from bytes.
///
/// Uses canonical deserialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if deserialization fails.
pub fn deserialize_proof(bytes: &[u8]) -> Result<Proof, ProverError> {
    Proof::deserialize_uncompressed(bytes).map_err(|e| ProverError::SerializationError(e.to_string()))
}

/// Serialize a verifying key to bytes.
///
/// Uses canonical serialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if serialization fails.
pub fn serialize_verifying_key(vk: &VerifyingKey) -> Result<Vec<u8>, ProverError> {
    let mut bytes = Vec::new();
    vk.serialize_uncompressed(&mut bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))?;
    Ok(bytes)
}

/// Deserialize a verifying key from bytes.
///
/// Uses canonical deserialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if deserialization fails.
pub fn deserialize_verifying_key(bytes: &[u8]) -> Result<VerifyingKey, ProverError> {
    VerifyingKey::deserialize_uncompressed(bytes).map_err(|e| ProverError::SerializationError(e.to_string()))
}

// ---------------------------------------------------------------------------
// Batch verification
// ---------------------------------------------------------------------------

/// Verify multiple Groth16 proofs individually.
///
/// NOTE: This function verifies each proof individually. True batch verification
/// (using random linear combinations) is future work.
///
/// TODO: Implement proper batch verification using random linear combinations
/// of pairing checks, reducing amortized verification cost from O(n) pairing
/// checks to O(1) pairing checks + O(n) group operations.
///
/// # Algorithm (current — individual verification)
///
/// Each proof is verified independently using [`verify_proof`]. The random
/// scalars derived from BLAKE3 are currently unused but are retained for
/// future optimization when proper batch pairing checks are implemented.
///
/// # Arguments
///
/// * `vk` — The verifying key (must be the same for all proofs)
/// * `proof_pairs` — Slice of (proof, public_inputs) pairs
///
/// # Returns
///
/// `Ok(true)` if all proofs verify, `Ok(false)` if any proof is invalid,
/// or `Err(ProverError)` if the verification algorithm fails.
///
/// # Security
///
/// Random scalars are derived from BLAKE3 with domain separation
/// `OMNIA-BATCH-VRFY-V1`, binding the randomness to the specific proofs
/// being verified. This prevents the prover from manipulating the aggregation.
pub fn verify_multiple(vk: &VerifyingKey, proof_pairs: &[(Proof, Vec<ark_bn254::Fr>)]) -> Result<bool, ProverError> {
    use ark_ff::PrimeField;
    use ark_serialize::CanonicalSerialize;

    if proof_pairs.is_empty() {
        return Ok(true);
    }

    // For a single proof, just use the standard verification
    if proof_pairs.len() == 1 {
        return verify_proof(vk, &proof_pairs[0].1, &proof_pairs[0].0);
    }

    // Serialize all proofs and public inputs for domain-separated randomness
    let mut transcript = Vec::new();
    for (i, (proof, inputs)) in proof_pairs.iter().enumerate() {
        transcript.extend_from_slice(&i.to_le_bytes());
        let mut proof_bytes = Vec::new();
        proof
            .serialize_compressed(&mut proof_bytes)
            .map_err(|e| ProverError::SerializationError(e.to_string()))?;
        transcript.extend_from_slice(&proof_bytes);
        for input in inputs {
            let mut input_bytes = Vec::new();
            input
                .serialize_compressed(&mut input_bytes)
                .map_err(|e| ProverError::SerializationError(e.to_string()))?;
            transcript.extend_from_slice(&input_bytes);
        }
    }

    // Generate random scalars using BLAKE3 for domain-separated randomness.
    // Note: OsRng is NOT used here because these scalars are currently unused
    // (individual verification is performed instead of true batch pairing
    // checks). When proper batch verification is implemented, the randomness
    // must be derived deterministically from the transcript to ensure
    // verification is reproducible.
    let random_scalars: Vec<ark_bn254::Fr> = (0..proof_pairs.len())
        .map(|i| {
            let mut hasher = blake3::Hasher::new();
            hasher.update(b"OMNIA-BATCH-VRFY-V1");
            hasher.update(&transcript);
            hasher.update(&i.to_le_bytes());
            let hash = hasher.finalize();
            ark_bn254::Fr::from_be_bytes_mod_order(hash.as_bytes())
        })
        .collect();

    // Individual verification for correctness (simplified approach)
    // A production implementation would use actual batch pairing checks
    // with MSM aggregation. For now, we verify each proof individually
    // but with the random scalar binding for future optimization.
    // TODO: Implement proper batch verification using random linear combinations.
    for (i, (proof, inputs)) in proof_pairs.iter().enumerate() {
        let _r_i = &random_scalars[i]; // Used for binding in future batch verification
        let result = verify_proof(vk, inputs, proof)?;
        if !result {
            return Ok(false);
        }
    }

    Ok(true)
}

/// Deprecated alias for [`verify_multiple`].
///
/// This function was renamed to `verify_multiple` to accurately reflect that
/// it verifies each proof individually rather than using true batch verification.
#[deprecated(
    since = "0.3.0",
    note = "Use verify_multiple instead — this function does not perform true batch verification"
)]
#[allow(deprecated)]
pub fn verify_proofs_batch(
    vk: &VerifyingKey,
    proof_pairs: &[(Proof, Vec<ark_bn254::Fr>)],
) -> Result<bool, ProverError> {
    verify_multiple(vk, proof_pairs)
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use crate::circuit::RollupCircuit;
    use ark_bn254::Fr;

    #[test]
    fn test_batch_verify_valid_proofs() {
        let circuit = RollupCircuit::empty();
        let (pk, vk) = generate_trusted_setup(&circuit).expect("setup failed");

        let mut proof_pairs = Vec::new();
        for i in 0u8..8 {
            let mut old = [0u8; 32];
            old[0] = i;
            let mut new = [0u8; 32];
            new[0] = i + 1;
            let circuit = RollupCircuit::from_state_roots(old, new, 5, old, new);
            let pub_input = circuit.public_input().expect("public input should be available");
            let proof = create_proof(circuit, &pk).expect("proof failed");
            proof_pairs.push((proof, pub_input));
        }

        let result = verify_multiple(&vk, &proof_pairs).expect("batch verify failed");
        assert!(result, "All valid proofs should batch verify");
    }

    #[test]
    fn test_batch_verify_one_invalid() {
        let circuit = RollupCircuit::empty();
        let (pk, vk) = generate_trusted_setup(&circuit).expect("setup failed");

        let mut proof_pairs = Vec::new();

        // 7 valid proofs
        for i in 0u8..7 {
            let mut old = [0u8; 32];
            old[0] = i;
            let mut new = [0u8; 32];
            new[0] = i + 1;
            let circuit = RollupCircuit::from_state_roots(old, new, 5, old, new);
            let pub_input = circuit.public_input().expect("public input should be available");
            let proof = create_proof(circuit, &pk).expect("proof failed");
            proof_pairs.push((proof, pub_input));
        }

        // 1 invalid proof (wrong public input)
        let mut old = [0u8; 32];
        old[0] = 7;
        let mut new = [0u8; 32];
        new[0] = 8;
        let circuit = RollupCircuit::from_state_roots(old, new, 5, old, new);
        let proof = create_proof(circuit, &pk).expect("proof failed");
        let wrong_public_inputs = vec![Fr::from(99999u64), Fr::from(99998u64)]; // Wrong!
        proof_pairs.push((proof, wrong_public_inputs));

        let result = verify_multiple(&vk, &proof_pairs).expect("batch verify failed");
        assert!(!result, "Batch with one invalid proof should fail");
    }

    #[test]
    fn test_batch_verify_empty() {
        let circuit = RollupCircuit::empty();
        let (_pk, vk) = generate_trusted_setup(&circuit).expect("setup failed");

        let result = verify_multiple(&vk, &[]).expect("batch verify failed");
        assert!(result, "Empty batch should verify as true");
    }
}
