//! Groth16 prover and verifier for the Omnia rollup circuit.
//!
//! This module provides three core operations:
//!
//! - **Trusted setup** — Generate the proving key and verifying key for a
//!   [`RollupCircuit`](crate::circuit::RollupCircuit).
//! - **Proof creation** — Create a Groth16 proof for a given circuit instance.
//! - **Proof verification** — Verify a Groth16 proof against a verifying key
//!   and public inputs.
//!
//! All operations use the Bn254 pairing-friendly curve and the
//! [`ark_groth16`] implementation.

use ark_bn254::Bn254;
use ark_crypto_primitives::snark::CircuitSpecificSetupSNARK;
use ark_groth16::Groth16;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;

use crate::circuit::RollupCircuit;

/// Errors that can occur during proving operations.
#[derive(Debug, thiserror::Error)]
pub enum ProverError {
    /// Error during trusted setup key generation.
    #[error("trusted setup failed: {0}")]
    SetupFailed(String),
    /// Error during proof creation.
    #[error("proof creation failed: {0}")]
    ProofCreationFailed(String),
    /// Error during proof verification.
    #[error("proof verification failed: {0}")]
    VerificationFailed(String),
    /// Error serializing or deserializing proof data.
    #[error("serialization error: {0}")]
    SerializationError(String),
    /// Error extracting public inputs from the circuit.
    #[error("circuit error: {0}")]
    CircuitError(String),
}

/// Proving key for Groth16 on Bn254.
pub type ProvingKey = ark_groth16::ProvingKey<Bn254>;

/// Verifying key for Groth16 on Bn254.
pub type VerifyingKey = ark_groth16::VerifyingKey<Bn254>;

/// Groth16 proof on Bn254.
pub type Proof = ark_groth16::Proof<Bn254>;

/// Generate a trusted setup (proving key and verifying key) for the rollup
/// circuit.
///
/// The trusted setup is circuit-specific but input-agnostic: it only depends
/// on the structure of the circuit (number of constraints, witnesses, and
/// public inputs), not on the actual values. A dummy circuit with zero values
/// is used to determine the structure.
///
/// # Arguments
///
/// * `circuit` — A reference to a [`RollupCircuit`] used to determine the
///   circuit structure. The actual witness values are not used for setup.
///
/// # Errors
///
/// Returns [`ProverError::SetupFailed`] if the key generation fails.
pub fn generate_trusted_setup(
    circuit: &RollupCircuit,
) -> Result<(ProvingKey, VerifyingKey), ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    let dummy_circuit = RollupCircuit::empty();

    // Use the dummy circuit for setup since only the structure matters
    let _ = circuit; // suppress unused variable warning
    Groth16::<Bn254>::setup(dummy_circuit, &mut rng)
        .map_err(|e| ProverError::SetupFailed(e.to_string()))
}

/// Create a Groth16 proof for the given circuit instance.
///
/// The proof can be verified by any party that holds the verifying key and
/// the public inputs.
///
/// # Arguments
///
/// * `circuit` — The [`RollupCircuit`] instance with assigned witnesses
///   and public inputs.
/// * `pk` — The proving key generated by [`generate_trusted_setup`].
///
/// # Errors
///
/// Returns [`ProverError::ProofCreationFailed`] if proof generation fails,
/// or [`ProverError::CircuitError`] if the public inputs cannot be extracted.
pub fn create_proof(circuit: RollupCircuit, pk: &ProvingKey) -> Result<Proof, ProverError> {
    let mut rng = ChaCha8Rng::from_entropy();
    Groth16::<Bn254>::prove(pk, circuit, &mut rng)
        .map_err(|e| ProverError::ProofCreationFailed(e.to_string()))
}

/// Verify a Groth16 proof against a verifying key and public inputs.
///
/// # Arguments
///
/// * `vk` — The verifying key generated by [`generate_trusted_setup`].
/// * `public_inputs` — The public inputs (expected new state root).
/// * `proof` — The Groth16 proof to verify.
///
/// # Errors
///
/// Returns [`ProverError::VerificationFailed`] if the verification algorithm
/// fails (not if the proof is invalid — an invalid proof returns `Ok(false)`).
pub fn verify_proof(
    vk: &VerifyingKey,
    public_inputs: &[ark_bn254::Fr],
    proof: &Proof,
) -> Result<bool, ProverError> {
    Groth16::<Bn254>::verify(vk, public_inputs, proof)
        .map_err(|e| ProverError::VerificationFailed(e.to_string()))
}

/// Serialize a Groth16 proof to bytes.
///
/// Uses canonical serialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if serialization fails.
pub fn serialize_proof(proof: &Proof) -> Result<Vec<u8>, ProverError> {
    let mut bytes = Vec::new();
    proof
        .serialize_uncompressed(&mut bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))?;
    Ok(bytes)
}

/// Deserialize a Groth16 proof from bytes.
///
/// Uses canonical deserialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if deserialization fails.
pub fn deserialize_proof(bytes: &[u8]) -> Result<Proof, ProverError> {
    Proof::deserialize_uncompressed(bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))
}

/// Serialize a verifying key to bytes.
///
/// Uses canonical serialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if serialization fails.
pub fn serialize_verifying_key(vk: &VerifyingKey) -> Result<Vec<u8>, ProverError> {
    let mut bytes = Vec::new();
    vk.serialize_uncompressed(&mut bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))?;
    Ok(bytes)
}

/// Deserialize a verifying key from bytes.
///
/// Uses canonical deserialization from `ark_serialize`.
///
/// # Errors
///
/// Returns [`ProverError::SerializationError`] if deserialization fails.
pub fn deserialize_verifying_key(bytes: &[u8]) -> Result<VerifyingKey, ProverError> {
    VerifyingKey::deserialize_uncompressed(bytes)
        .map_err(|e| ProverError::SerializationError(e.to_string()))
}
