//! # Omnia Protocol — Layer 2: Domain Shards
//!
//! Domain shards are specialized state machines that build on top of the
//! Layer 1 substrate. Each shard type has its own:
//!
//! - **State machine** — defines what operations are valid and how they
//!   mutate state
//! - **Validation rules** — domain-specific constraints (e.g., sufficient
//!   balance for transfers)
//! - **CRDT semantics** — how state converges when events arrive in
//!   different orders
//!
//! But all shards share:
//! - The same **causal graph** for event ordering
//! - The same **consensus** for finality
//! - The same **gossip protocol** for propagation
//!
//! # The 6 Shard Types
//!
//! | Shard         | Domain                   | State Type                   |
//! |---------------|--------------------------|------------------------------|
//! | Financial     | Assets, value transfer   | Account balances (causal)    |
//! | Computational | AI training, compute     | Task queue, proof registry   |
//! | Physical      | Supply chain, real estate| Provenance log (append-only) |
//! | Biological    | Health records, bio      | Consent registry, ZK queries |
//! | Identity      | DIDs, social recovery    | DID document registry        |
//! | Economics     | UBC, useful work, gov    | Quota system, governance     |
//!
//! # Architecture
//!
//! All six shards follow the same structural pattern (struct holding state,
//! `Shard` trait impl), which is generated by the `impl_shard!`
//! macro. The [`ShardState`] trait normalizes the `apply` call so the
//! macro can use a uniform dispatch.
//!
//! # Usage
//!
//! ```ignore
//! use omnia_shards::{FeeSchedule, ShardRouter, FinancialShard, IdentityShard};
//! use omnia_economics::QuotaSystem;
//!
//! let mut router = ShardRouter::new(FeeSchedule::standard(), QuotaSystem::default_system());
//! router.register(Box::new(FinancialShard::new()));
//! router.register(Box::new(IdentityShard::new()));
//!
//! // Route an event to the appropriate shard
//! router.route_event(&event)?;
//! ```

#![deny(clippy::unwrap_used)]
#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod biological;
pub mod computational;
pub mod cross_shard;
pub mod domain_state;
pub mod economics_shard;
pub mod fee_schedule;
pub mod financial;
pub mod identity;
#[doc(hidden)]
pub mod macros;
pub mod nonce_store;
pub mod payload;
pub mod physical;
pub mod router;
pub mod shard;
pub mod validator;
pub mod zk;

// Re-export core types
pub use cross_shard::CrossShardMessage;
pub use domain_state::ShardState;
pub use economics_shard::{EconomicsOp, EconomicsVoteChoice};
pub use fee_schedule::FeeSchedule;
pub use nonce_store::{InMemoryNonceStore, NonceStore, NonceStoreError, RedbNonceStore};
pub use payload::{ShardOp, ShardPayload};
pub use router::{MutexShardRouter, ShardRouter};
pub use shard::{Shard, ShardError, ShardId};
pub use validator::DomainValidator;

// Re-export shard-specific types for convenience
pub use biological::{BiologicalOp, BiologicalState, BiologicalValidator, ConsentRecord};
pub use computational::{ComputationalOp, ComputationalState, ComputationalValidator, TaskStatus};
pub use financial::{AccountBalance as FinancialAccountBalance, FinancialOp, FinancialState, FinancialValidator};
pub use identity::{
    format_did, AgentCapability, AgentIdentity, BiometricAnchor, Did, DidDocument, DidError, DidUpdate, EncryptedShare,
    IdentityOp, IdentityState, IdentityValidator, RecoveryConfig, RecoveryShare, ShamirRecovery, DID_METHOD,
    DID_PREFIX,
};
pub use physical::{PhysicalOp, PhysicalState, PhysicalValidator, ProvenanceEvent};

// ---------------------------------------------------------------------------
// Concrete shard implementations (generated by impl_shard! macro)
// ---------------------------------------------------------------------------

impl_shard!(
    /// The Financial shard — handles asset transfers, minting, and burning.
    ///
    /// Uses strict causal ordering (not CRDTs) for balance updates because
    /// financial operations like transfers are not commutative.
    FinancialShard,
    FinancialState,
    FinancialOp,
    ShardOp::Financial,
    FinancialValidator,
    ShardId::financial()
);

impl_shard!(
    /// The Identity shard — handles DID lifecycle and social recovery.
    IdentityShard,
    IdentityState,
    IdentityOp,
    ShardOp::Identity,
    IdentityValidator,
    ShardId::identity()
);

impl_shard!(
    /// The Computational shard — handles AI training tasks and proof verification.
    ComputationalShard,
    ComputationalState,
    ComputationalOp,
    ShardOp::Computational,
    ComputationalValidator,
    ShardId::computational()
);

impl_shard!(
    /// The Physical shard — handles supply chain and real-world asset provenance.
    PhysicalShard,
    PhysicalState,
    PhysicalOp,
    ShardOp::Physical,
    PhysicalValidator,
    ShardId::physical()
);

impl_shard!(
    /// The Biological shard — handles health records and consent management.
    BiologicalShard,
    BiologicalState,
    BiologicalOp,
    ShardOp::Biological,
    BiologicalValidator,
    ShardId::biological()
);

impl_shard!(
    /// The Economics shard — handles UBC tokens, useful work rewards, and governance.
    ///
    /// Delegates state management to [`omnia_economics::EconomicsState`],
    /// which provides the full quota system, governance (quadratic voting
    /// with decay), and useful-work proof verification.
    EconomicsShard,
    omnia_economics::EconomicsState,
    omnia_economics::EconomicsOp,
    ShardOp::Economics,
    EconomicsValidator,
    ShardId::economics()
);

// ---------------------------------------------------------------------------
// Economics validator — inline because it validates the canonical
// EconomicsOp from omnia_economics (which uses UsefulWorkProof, not Vec<u8>)
// ---------------------------------------------------------------------------

/// Validator for the Economics shard.
///
/// Performs pre-flight checks on [`EconomicsOp`] variants. The
/// `SubmitWork` variant is not pre-flight-validated here because
/// proof verification requires the full economics state machine;
/// it is validated inside `EconomicsState::apply`.
pub struct EconomicsValidator;

impl EconomicsValidator {
    /// Validate an economics operation against the given state.
    pub fn validate(
        _state: &omnia_economics::EconomicsState,
        op: &omnia_economics::EconomicsOp,
    ) -> Result<(), ShardError> {
        match op {
            omnia_economics::EconomicsOp::SpendUbc { amount, .. } if *amount == 0 => {
                Err(ShardError::ValidationFailed("Spend amount must be > 0".into()))
            }
            omnia_economics::EconomicsOp::MintUbc { amount, .. } if *amount == 0 => {
                Err(ShardError::ValidationFailed("Mint amount must be > 0".into()))
            }
            _ => Ok(()),
        }
    }
}
